export const NIGERIAN_MARKETS = [
  { state: "Abia", markets: ["Ariaria International Market", "Cemetery Market", "Ahia Ohuru (New Market)"] },
  { state: "Adamawa", markets: ["Jimeta Main Market", "Yola Town Market", "Mubi International Market"] },
  { state: "Akwa Ibom", markets: ["Itam Market", "Akpan Andem Market", "Urua Ekpa Market"] },
  { state: "Anambra", markets: ["Onitsha Main Market", "Nnewi Nkwo Market", "Ochanja Market", "Eke Awka Market"] },
  { state: "Bauchi", markets: ["Wunti Market", "Mudanbe Market", "Azare Market"] },
  { state: "Bayelsa", markets: ["Swali Market", "Kpansia Market", "Tombia Market"] },
  { state: "Benue", markets: ["Wurukum Market", "Wadata Market", "Modern Market Makurdi", "Zaki Biam Yam Market"] },
  { state: "Borno", markets: ["Monday Market", "Baga Road Market", "Customs Market"] },
  { state: "Cross River", markets: ["Watt Market", "Marian Market", "Ikom Market"] },
  { state: "Delta", markets: ["Ogbeogonogo Market", "Main Market Asaba", "Igbudu Market (Warri)"] },
  { state: "Ebonyi", markets: ["Abakpa Main Market", "Kpirikpiri Market", "International Market Abakaliki"] },
  { state: "Edo", markets: ["Oba Market", "New Benin Market", "Uselu Market", "Ekiosa Market"] },
  { state: "Ekiti", markets: ["Oja Oba (Ado Ekiti)", "Bisi Market", "Fayose Market"] },
  { state: "Enugu", markets: ["Ogbete Main Market", "Kenyatta Market", "New Market"] },
  { state: "Federal Capital Territory (Abuja)", markets: ["Wuse Market", "Garki International Market", "Utako Market", "Gudu Market"] },
  { state: "Gombe", markets: ["Gombe Main Market", "Kasuwan Mata", "Bima Market"] },
  { state: "Imo", markets: ["Eke Ukwu Owerri", "Relief Market", "Orlu Main Market"] },
  { state: "Jigawa", markets: ["Maigatari International Market", "Hadejia Market", "Kazaure Market"] },
  { state: "Kaduna", markets: ["Kaduna Central Market", "Kasuwan Barchi", "Panteka Market"] },
  { state: "Kano", markets: ["Kurmi Market", "Kantin Kwari Market", "Dawanau Market", "Sabon Gari Market"] },
  { state: "Katsina", markets: ["Katsina Central Market", "Daura Market", "Funtua Market"] },
  { state: "Kebbi", markets: ["Birnin Kebbi Central Market", "Jega Market", "Argungu Market"] },
  { state: "Kogi", markets: ["Lokoja International Market", "Kpata Market", "Anyigba Market"] },
  { state: "Kwara", markets: ["Ipata Market", "Oja Oba (Ilorin)", "Mandate Market", "Tayo Market"] },
  { state: "Lagos", markets: ["Alaba International Market", "Balogun Market", "Computer Village", "Idumota Market", "Trade Fair Complex", "Oshodi Market", "Mile 12 Market"] },
  { state: "Nasarawa", markets: ["Lafia Modern Market", "Karu Market", "Keffi Main Market"] },
  { state: "Niger", markets: ["Minna Central Market", "Kure Modern Market", "Bida Main Market", "Suleja Market"] },
  { state: "Ogun", markets: ["Kuto Market", "Omida Market", "Sapon Market", "Lafenwa Market"] },
  { state: "Ondo", markets: ["Oja Oba (Akure)", "Isinkan Market", "Adaba Market"] },
  { state: "Osun", markets: ["Oja Oba (Osogbo)", "Igbona Market", "Oluode Market"] },
  { state: "Oyo", markets: ["Bodija Market", "Oje Market", "Gbagi Market", "Auto Spare Parts Market (Gate)"] },
  { state: "Plateau", markets: ["Terminus Market", "Katako Market", "Building Materials Market Jos"] },
  { state: "Rivers", markets: ["Mile 1 Market", "Mile 3 Market", "Oil Mill Market", "Building Materials Market (Ikokwu)"] },
  { state: "Sokoto", markets: ["Sokoto Central Market", "Kara Market", "Old Market"] },
  { state: "Taraba", markets: ["Jalingo Main Market", "Wukari Market", "Mutum Biyu Market"] },
  { state: "Yobe", markets: ["Damaturu Main Market", "Potiskum Cattle Market", "Gashua Market"] },
  { state: "Zamfara", markets: ["Gusau Central Market", "Kauran Namoda Market", "Talata Mafara Market"] },
];
